[pacman]
packages = [
    "amd-ucode",                 # Not sure what this does
    "android-tools",             # For adb I guess
    "base",                      # Base arch
    "base-devel",                # group of dev tools like make, automake, autoconf, bison
    "bluez-utils",               # bluetooth
    "btrfs-progs",               # user space utilities for btrfs
    "cmake",
    "cups",                      # printer daemon
    "cups-pdf",                  # Not sure if needed, it adds some common stuff for cups
    "efitools",                  # Edit EFI entries from arch
    "perl-image-exiftool",       # Edit images metadata
    "emacs",
    "firefox",                   # Not flatpak since keepassxc won't work
    "flatpak",
    "gdm",                       # Lock screen before login
    "ghostty",                   # Terminal emulator
    "git",
    "gnome-backgrounds",         # Desktop images
    "gnome-browser-connector",   # For extension install
    "gnome-calculator",
    "gnome-calendar",
    "gnome-clocks",
    "gnome-control-center",
    "gnome-disk-utility",
    "gnome-font-viewer",
    "gnome-keyring",           # Gnome password manager
    "gnome-menus",             # A base for many gnome packages
    "gnome-session",           # Start the shell and the user session in general
    "gnome-settings-daemon",   # Stores gnome settings
    "gnome-shell",             # The shell for the DE
    "gnome-shell-extensions",  # Manage gnome extensions
    "gnome-software",          # Flatpak browser
    "gnome-tweaks",
    "openbsd-netcat",        # Provide the nc utility
    "gvfs",                  # Various virtual file systems for the gnome file explorer
    "gvfs-afc",              # Apple files
    "gvfs-goa",              # Links with your gnome online accounts
    "gvfs-google",           # Google drive
    "gvfs-mtp",              # For android files
    "gvfs-smb",
    "hplip",                 # HP printer
    "htop",
    "iwd",                   # wireless setup
    "linux-firmware",
    "linux-lts",
    "linux-zen",
    "loupe",
    "malcontent",
    "man-db",
    "meson",
    "mlt",
    "nautilus",
    "networkmanager",
    "net-tools",              # netstat among others
    "ninja",
    "npm",
    "opentimelineio",
    "orca",
    "pacman-contrib",
    "plocate",
    "podman",
    "power-profiles-daemon",
    "pnpm",                  # npm but with caching across projects
    "python-pip",
    "refind",                # UEFI only bootloader
    "sbsigntools",           # to sign the bootloader
    "steam",
    "sudo",
    "tailscale",
    "timeshift",
    "tmux",
    "totem",                 # GNOME video player
    "uv",                    # Python package manager
    "vim",
    "wget",
]

[uv]
packages = [
    "clangd",
    "clang-format",
    "python-lsp-server",
    "ruff"
]

[flatpak]
packages = [
    "com.google.AndroidStudio",              # Android IDE
    "io.github.kolunmi.Bazaar",              # Software store, alternative to GNOME Software
    "org.gnome.Boxes",                       # GNOME VM frontend
    "com.google.Chrome",                     # Alternative web browser
    "org.gimp.GIMP",                         # Image editor
    "com.heroicgameslauncher.hgl",           # Alternative game launcher for gog gaming
    "org.kde.kdenlive",                      # Video editor
    "org.keepassxc.KeePassXC",               # Password manager
    "com.warlordsoftwares.media-downloader", # Youtube downloader
    "io.missioncenter.MissionCenter",        # System monitor
    "com.synology.SynologyDrive",            # Sync nas/pc
    "dev.deedles.Trayscale",                 # Tailscale
    "org.mozilla.Thunderbird",               # Mail client
    "org.onlyoffice.desktopeditors",         # Office suite
    "org.videolan.VLC",                      # Video player
]

[paru]
packages = [
    "beautyline",    # Icon pack
    "paru",          # AUR package manager
    "paru-debug",    # I guess installed automatically when installing paru ?
    "shim-signed",   # Signing the kernel with some keys for secure boot
]

